<a href="https://colab.research.google.com/github/ahn19/tensorflow_ex/blob/main/1_2_TensorFlow_Basics_2_0_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x # 2.x버전이후로 1.x를 쓰고 싶다면 "%tensorflow_version 1.x"라고 수정하면 된다. 이건 colab에서만되는 기능이다
  # 주피터 노트북에서는 안된다.
except Exception:
  pass


In [3]:
import numpy as np
import tensorflow as tf

In [4]:
print (tf.__version__)

2.4.1


In [5]:
tf.executing_eagerly()

True

## Defining Tensors

In [6]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
              [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

In [7]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [8]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [9]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [10]:
print(t1)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


## Numpy Compatibility

In [11]:
ndarray = np.ones([3, 3])

print("TensorFlow operations convert numpy arrays to Tensors automatically")
tensor = tf.multiply(ndarray, 42)
print(tensor)


print("And NumPy operations convert Tensors to numpy arrays automatically")
print(np.add(tensor, 1))

print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())
ndarray

TensorFlow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And NumPy operations convert Tensors to numpy arrays automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Constants

In [12]:
hello = tf.constant("Hello World!")
print(hello)

tf.Tensor(b'Hello World!', shape=(), dtype=string)


In [13]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print(a.numpy())
print(b)

1.5
tf.Tensor(2.5, shape=(), dtype=float32)


## Operations


In [14]:
a_plus_b = tf.add(a, b)
print(a_plus_b)

tf.Tensor(4.0, shape=(), dtype=float32)


In [15]:
a_mul_b = tf.multiply(a, b)
print(a_mul_b)

tf.Tensor(3.75, shape=(), dtype=float32)


## Variables

In [17]:
weight = tf.Variable(tf.random_normal_initializer(stddev=0.1)([5, 2]))
print(weight)

<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[-0.05451545,  0.22433305],
       [ 0.13045388,  0.05415407],
       [ 0.11545224, -0.02186006],
       [-0.08323954, -0.02641266],
       [ 0.05867658, -0.02265279]], dtype=float32)>


## Create a Dataset

In [47]:
a = np.arange(10)
print(a)
ds_tensors = tf.data.Dataset.from_tensor_slices(a)

[0 1 2 3 4 5 6 7 8 9]


## Apply Transformations

In [27]:
ds_tensors0 = ds_tensors.map(tf.square)
print(ds_tensors0)

<MapDataset shapes: (), types: tf.int64>


In [48]:
ds_tensors = ds_tensors.map(tf.square).shuffle(20).batch(2)
# ds_tensors = ds_tensors.map(tf.square).batch(2)

In [43]:
# import pdb;pdb.set_trace()
np.size(ds_tensors)

1

## Iterate

In [49]:
print('Elements of ds_tensors:')
for _ in range(3):
  for x in ds_tensors:
    print(x)

Elements of ds_tensors:
tf.Tensor([ 0 16], shape=(2,), dtype=int64)
tf.Tensor([64  9], shape=(2,), dtype=int64)
tf.Tensor([36 81], shape=(2,), dtype=int64)
tf.Tensor([ 4 49], shape=(2,), dtype=int64)
tf.Tensor([ 1 25], shape=(2,), dtype=int64)
tf.Tensor([ 1 49], shape=(2,), dtype=int64)
tf.Tensor([25 81], shape=(2,), dtype=int64)
tf.Tensor([64 36], shape=(2,), dtype=int64)
tf.Tensor([ 9 16], shape=(2,), dtype=int64)
tf.Tensor([0 4], shape=(2,), dtype=int64)
tf.Tensor([ 9 16], shape=(2,), dtype=int64)
tf.Tensor([ 4 25], shape=(2,), dtype=int64)
tf.Tensor([81 49], shape=(2,), dtype=int64)
tf.Tensor([ 0 36], shape=(2,), dtype=int64)
tf.Tensor([64  1], shape=(2,), dtype=int64)
