<a href="https://colab.research.google.com/github/ahn19/tensorflow_ex/blob/main/1_2_TensorFlow_Basics_1_x_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip uninstall tensorflow

Uninstalling tensorflow-2.4.1:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/dist-packages/tensorflow-2.4.1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/tensorflow/*
Proceed (y/n)? y









  Successfully uninstalled tensorflow-2.4.1


In [2]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3MB 42kB/s 
     |████████████████████████████████| 3.8MB 41.3MB/s 
     |████████████████████████████████| 51kB 4.2MB/s 
     |████████████████████████████████| 512kB 55.4MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp37-none-any.whl size=7540 sha256=f0bc0a26565176de02cbb109e9c6b9931c25f1664273679d4f6d3c95bc77daea
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.12.1 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninstalled tensorboard-2.4.1
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tens

In [3]:
import numpy as np
import tensorflow as tf

In [4]:
print (tf.__version__)

1.15.0


## Defining Tensors

In [5]:
m1 = [[1.0, 2.0], 
      [3.0, 4.0]]
m2 = np.array([[1.0, 2.0],
              [3.0, 4.0]], dtype=np.float32)
m3 = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

In [6]:
print(type(m1))
print(type(m2))
print(type(m3))

<class 'list'>
<class 'numpy.ndarray'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [7]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [8]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>
<class 'tensorflow.python.framework.ops.Tensor'>


In [42]:
sess = tf.Session()
print ("OPEN SESSION")

OPEN SESSION


In [43]:
def print_tf(x):
    print("TYPE IS\n %s" % (type(x)))
    print("VALUE IS\n %s" % (x))

## Constants

In [11]:
hello = tf.constant("Hello World!")
print(hello)
print_tf(hello)

Tensor("Const_3:0", shape=(), dtype=string)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_3:0", shape=(), dtype=string)


In [12]:
hello_out = sess.run(hello)
print_tf(hello_out)

TYPE IS
 <class 'bytes'>
VALUE IS
 b'Hello World!'


In [13]:
a = tf.constant(1.5)
b = tf.constant(2.5)
print_tf(a)
print_tf(b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_4:0", shape=(), dtype=float32)
TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Const_5:0", shape=(), dtype=float32)


In [14]:
a_out = sess.run(a)
b_out = sess.run(b)
print_tf(a_out)
print_tf(b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 1.5
TYPE IS
 <class 'numpy.float32'>
VALUE IS
 2.5


## Operations


In [15]:
a_plus_b = tf.add(a, b)
print_tf(a_plus_b)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Add:0", shape=(), dtype=float32)


In [16]:
a_plus_b_out = sess.run(a_plus_b)
print_tf(a_plus_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 4.0


In [17]:
a_mul_b = tf.multiply(a, b)
a_mul_b_out = sess.run(a_mul_b)
print_tf(a_mul_b_out)

TYPE IS
 <class 'numpy.float32'>
VALUE IS
 3.75


## Variables

In [46]:
weight = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight)

TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable_4:0' shape=(5, 2) dtype=float32_ref>


In [45]:
tf.Variable? # tf.Variable에 대한 도움말을 창으로 띄워 알려준다. 

SyntaxError: ignored

In [47]:
weight_out = sess.run(weight)# 초기화 해주지 않으니 에러가 난다
print_tf(weight_out)

FailedPreconditionError: ignored

In [48]:
sess.run(weight.initializer)

In [49]:
weight_out = sess.run(weight)
print_tf(weight_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[ 0.0870043   0.02938111]
 [ 0.00641669  0.01144468]
 [ 0.07312305  0.10050172]
 [-0.04292301 -0.05292813]
 [ 0.11597325  0.05817398]]


In [24]:
weight2 = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
weight3 = tf.Variable(tf.random_normal([5, 2], stddev=0.1))
print_tf(weight2)
print_tf(weight3)

TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable_1:0' shape=(5, 2) dtype=float32_ref>
TYPE IS
 <class 'tensorflow.python.ops.variables.RefVariable'>
VALUE IS
 <tf.Variable 'Variable_2:0' shape=(5, 2) dtype=float32_ref>


In [50]:
# weight1, 2, 3과 같은 weights들을 100개 만들었다면 일일이 초기화해주기는 어려우니, 
# global_variables_initializer()를 만들고 sess.run(init)하면 모두 한꺼번에 초기화해준다. 
init = tf.global_variables_initializer()
sess.run(init)

In [29]:
weight_out2 = sess.run(weight2)
weight_out3 = sess.run(weight3)
print_tf(weight_out2)
print_tf(weight_out3)

RuntimeError: ignored

In [38]:
# 변수생성에는 tf.Variable과 tf.get_variable()이 있는데 get_variable을 추천했었다. 
# 하지만 현재 tf.get_variable()은 없어졌다.
s = tf.Variable(2, name='scalar') 
m = tf.Variable([[0, 1], [2, 3]], name='matrix') 
W = tf.Variable(tf.zeros([784,10]), name='big_matrix')
V = tf.Variable(tf.truncated_normal([784, 10]), name='normal_matrix')

# s = tf.get_variable('scalar', initializer=tf.constant(2)) 
# m = tf.get_variable('matrix', initializer=tf.constant([[0, 1], [2, 3]]))
# W = tf.get_variable('big_matrix', shape=(784, 10), initializer=tf.zeros_initializer())
# V = tf.get_variable('normal_matrix', shape=(784, 10), initializer=tf.truncated_normal_initializer())

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(V.eval())

[[-0.57949847 -0.69303703 -0.63523334 ...  1.6019208   0.29710448
  -0.39792407]
 [ 0.6161155   0.08669081 -0.34414172 ...  1.2803761  -1.4620309
  -1.2684935 ]
 [ 0.39432716  0.96497256 -1.6113836  ... -1.4255372  -0.26769054
  -0.43668538]
 ...
 [-0.57173586  0.76670474 -0.7162282  ...  0.53179723  1.0693723
  -0.9771989 ]
 [-0.80520564  0.11125514  0.15588747 ... -0.8787712  -1.088076
  -0.28955638]
 [ 0.28662643  1.0143216  -0.7719866  ...  0.71116954  0.4421791
   1.5949156 ]]


*케라스의 하이레벨 api를 쓰지 않고 커스텀하게 명시적으로 레이어를 만들고자 할 때 variable로 웨이트와 바이어스는 tf.Variable로 선언한다는 것을 알아둬야*

## Placeholders

*training할 때와 test할 때, inference할 때 달라지는, 그때그때 상황에 따라 값이 달라지는 것들을 placeholder라고 해서, 공간만 만들어놓고 run할 때 값을 넣어주는 식으로 쓰기 위해 placeholder를 씀. *

In [51]:
x = tf.placeholder(tf.float32, [None, 5]) # 1번에 none을 쓰면 입력에 맞게 채워진다. 10개가 입력되면 None에는 2가 채워짐.
# 맨 처음 자리에는 데이터 개수가 들어갈 자리다. train할 때는 배치개수가 들어갈 자리. test시에는 테스트데이터 개수가 들어갈 자리.
print_tf(x)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("Placeholder_2:0", shape=(?, 5), dtype=float32)


In [52]:
oper = tf.matmul(x, weight)
print_tf(oper)

TYPE IS
 <class 'tensorflow.python.framework.ops.Tensor'>
VALUE IS
 Tensor("MatMul_2:0", shape=(?, 2), dtype=float32)


In [53]:
#sess = tf.Session()
data = np.random.rand(1, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.02000172 -0.00435628]]


In [54]:
data = np.random.rand(2, 5)
oper_out = sess.run(oper, feed_dict={x: data})
print_tf(oper_out)

TYPE IS
 <class 'numpy.ndarray'>
VALUE IS
 [[-0.07408237  0.10081761]
 [ 0.1441706   0.16713405]]


In [ ]:
sess.close()